# Site settings
title: Lovebeauty for beauty lovers
tagline: Beta Testers Sign Up Page
email: jinpeiios@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the sign up page for Lovebeauty beta users and testers.
baseurl: "/Lovebeauty-beta-testers" # the subpath of your site, e.g. /blog/
logourl: "http://i.imgur.com/dFuP4yp.png" # Site logo
author: "Jinpei Li"
author_thumbnail: "https://avatars2.githubusercontent.com/u/313377?v=3&s=140" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: gayanvirajith
    twitter: gayanvirajith
    facebook: gayanvirajith
    gplus: +gayanvirajith
    # dribble: gayanvirajith
    pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: false

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
